Repository sky-uk/toolkit, pull requests merged in 2018-04, with the labels that each got.

#395 Linting Tweaks
  .eslintrc
  .stylelintrc
  package.json
  packages/sky-toolkit-core/index.js
  packages/sky-toolkit-core/package.json
  packages/sky-toolkit-core/test/functional/sass-true.js
  packages/sky-toolkit-ui/package.json
  packages/sky-toolkit-ui/test/functional/sass-true.js
  packages/sky-toolkit/index.js
  preview/test/.eslintrc
Labels: bug, enhancement

#393 Fix for is-disabled styling when applied to c-select
  packages/sky-toolkit-ui/components/_select.scss
  packages/sky-toolkit-ui/docs/components/select.md
Labels: bug, ready

#347 Subsection Dividers
  packages/sky-toolkit-core/tools/_divider.scss
  packages/sky-toolkit-ui/components/_divider.scss
  packages/sky-toolkit-ui/docs/components/divider.md
Labels: ready

#402 Removed spread operator from tools/_functions in toolkit-core
  packages/sky-toolkit-core/tools/_functions.scss
Labels: bug, reviews needed, toolkit-core

#407 Update PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#404 Allow Extension of Gradient Directions
  packages/sky-toolkit-core/settings/_gradients.scss
Labels: enhancement, feature, toolkit-core
